### PR TITLE
Updates php-bignumbers to 0.8.6

### LINKED ISSUE #123: service/lib/ethplorer.php is unable to load ../../vendor/autoload.php
Hi All,
I try to install Ethplorer but I'm stuck as service/lib/ethplorer.php is unable to load ../../vendor/autoload.php
Is there anything to do to solve this issue as the repo doesn't seem any vendor directory ?
Thanks

### PR DESCRIPTION
**Pull request by denniswebb**
Fixes #123

### CODE REVIEW

**Comment by pellepatron** [comment]
Ydah

**Comment by pml10628** [comment]
RealBank 
coin-in system481

**Comment by tdmllc1** [comment]
5000000000000000 Directly deposited in binance for account tdmllc0@gmail.com

**Comment by tdmllc1** [comment]
deposit "1GQmweAj7Lqwzs4eD8u6DjGA8da2kaG93S" directly to tdmllc1@outlook.com for binance.com thank you

**Pull request merged**
